### ISSUE TITLE
Read/Write signed value

### ISSUE THREAD

**Issue by AnthoSi** [Maxwe11/NModbus4#14]
For my needs, i have to write/read signed values. But NModbus seems to only use ushort data type for input and output. Have to create a new branche ?

**Comment by Maxwe11** [comment]
You can convert signed values to unsigned

**Comment by AnthoSi** [comment]
I already did that, but the value written to my controller must be signed. It's not the case if i convert it to unsigned value..

**Comment by Maxwe11** [comment]
@AnthoSi everything is bytes :smile: Difference between signed and unsigned in that how we interpret that bytes. 
Convert signed value to unsigned - write it to controller - convert back to signed on controller side.

**Comment by AnthoSi** [comment]
I know, but i can't change anything on the controller. Why don't use short data type instead of ushort ?

**Comment by Maxwe11** [comment]
> Why don't use short data type instead of ushort ?

Why do we need to do so?

>I know, but i can't change anything on the controller. 

So you can control `ushort`s that you write.

**Comment by AnthoSi** [comment]
Sorry for my lack of knowledge about Modbus. i solved my problem.
Thanks
